/* Regenerate src/ds/components.css from the design-system bundle.
 *
 * The DS bundle (src/ds/bundle.js) is a browser IIFE that injects each
 * component's CSS at RUNTIME via document.createElement('style'), guarded by
 * `typeof document !== 'undefined'`. On the static, zero-JS build that guard is
 * false and no client JS runs, so those rules never land. This script runs the
 * bundle under a document shim that captures every injected <style>, and writes
 * them to src/ds/components.css (imported by ds/index.js so Astro bundles them).
 *
 * Re-run whenever ds/bundle.js changes:  node scripts/extract-ds-css.mjs
 */
import React from 'react';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

globalThis.window = globalThis;
globalThis.React = React;
const collected = [];
globalThis.document = {
  getElementById: () => null,
  createElement: () => ({}),
  head: { appendChild: (s) => { if (s && s.textContent) collected.push(s.textContent); } },
};

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
await import(resolve(root, 'src/ds/bundle.js'));

const header =
  '/* Auto-generated by scripts/extract-ds-css.mjs — the component styles the DS\n' +
  '   bundle injects at runtime, captured so the static (zero-JS) build ships them.\n' +
  '   Do not edit by hand; re-run the script if ds/bundle.js changes. */\n';
writeFileSync(resolve(root, 'src/ds/components.css'), header + collected.join('\n'));
console.log(`extracted ${collected.length} style blocks -> src/ds/components.css`);
